import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ToastNotification from "@/components/ui/ToastNotification";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";
import NavBarComponent from "@/components/NavBarComponent";
import { ThemeProvider } from "@/components/theme-provider";
import { ScrollArea, ScrollBar } from '@/components/ui/scroll-area'
import { useEffect, useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

          <SidebarProvider>
            <AppSidebar />
            <main className="flex-1 flex flex-col">
              <NavBarComponent>
                <SidebarTrigger />
              </NavBarComponent>
              <ScrollArea aria-orientation='horizontal'>
                {children}
                <ScrollBar orientation="horizontal" className="w-full" />
              </ScrollArea>
            </main>
          </SidebarProvider>
          <ToastNotification />

        </ThemeProvider>

      </body>
    </html>
  );
}

